---
configuration:
  template_base: "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}/"
domainname: crumpton.org
ldap:
  service:
    hostname: ldapint.crumpton.org
    ext_hostname: ldap.eaglecreek.work
    port: 636
    schema: ldaps
    bindanonymous: true 
    basedn: dc=crumpton,dc=org
    manager: cn=admin
