# SPDX-License-Identifier: MIT
---
configuration:
  template_base: "{{ ansible_distribution }}/"

sshd:
  server:
    authorized_keys_command: /usr/local/bin/authorized_keys_ldap
  service:
    denygroups: denyssh

paths:
  bash: /bin/bash
  sshd_config: /etc/ssh/sshd_config
  nss_ldap_conf: /usr/local/etc/nss_ldap.conf
  nss_switch_conf: /etc/nsswitch.conf
  eaglecreek_crt: /etc/ssl/eaglecreek.pem
  openldap_conf: /etc/openldap/ldap.conf
  login_ldap_conf: /etc/login_ldap.conf
  ypldap_conf: /etc/ypldap.conf
  domainname: /etc/defaultdomain
  login_conf: /etc/login.conf
