# SPDX-License-Identifier: MIT
---
  - include_tasks: freebsd.yml
    when: ansible_distribution == "FreeBSD"
  - include_tasks: debian.yml
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  - include_tasks: openbsd.yml
    when: ansible_distribution == "OpenBSD"
