---
# SPDX-License-Identifier: MIT
- name: Restart Wiki.js
  ansible.builtin.service:
    name: wikijs
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded