# SPDX-License-Identifier: MIT
# Wiki.js defaults
wikijs_version: "2.5.308"
wikijs_install_dir: /opt/wikijs
wikijs_data_dir: /var/lib/wikijs

# PostgreSQL defaults
wikijs_db_name: wikijs
wikijs_db_user: wikijs
wikijs_db_password: "ChangeMe!"
wikijs_db_host: "127.0.0.1"
wikijs_db_port: 5432

# System user
wikijs_user: wikijs
wikijs_group: wikijs
