# SPDX-License-Identifier: MIT
---
hostname: wiki-js
vmid: 514
node: pve02
storage: local-lvm
tags_list: docker, ldap, terraformed, u2204, ubuntu
features:
  nesting: true
networks:
  - name: eth0
    bridge: vmbr0
    ip: dhcp
    ip6: dhcp
